trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: bash scripts/create-servicebus.sh
  displayName: 'Create Service Bus Namespaces'

- script: bash scripts/create-geo-dr.sh
  displayName: 'Configure Geo-Disaster Recovery'

- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    command: 'buildAndPush'
    repository: 'myregistry.azurecr.io/transaction-processor'
    dockerfile: 'app/Dockerfile'
    tags: 'latest'

- script: bash scripts/aks-deploy.sh
  displayName: 'Deploy Application to AKS'
