apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-processor
  template:
    metadata:
      labels:
        app: transaction-processor
    spec:
      containers:
      - name: processor
        image: myregistry.azurecr.io/transaction-processor:latest
